GLM_FORCE_MESSAGES = False

GLM_FORCE_DEPTH_ZERO_TO_ONE = False

GLM_FORCE_LEFT_HANDED = False

GLM_FORCE_SIZE_T_LENGTH = False





GLM_MESSAGE_VERSION_DISPLAYED = False
GLM_MESSAGE_MODEL_DISPLAYED = False
GLM_MESSAGE_PLATFORM_DISPLAYED = False
GLM_MESSAGE_SWIZZLE_DISPLAYED = False
GLM_MESSAGE_DEPTH_DISPLAYED = False
GLM_MESSAGE_HANDED_DISPLAYED = False
GLM_MESSAGE_FORCE_SIZE_T_LENGTH = False
GLM_MESSAGE_CORE_INCLUDED_DISPLAYED = False
